# https://kubernetes.io/docs/concepts/configuration/secret/

apiVersion: v1
kind: Secret # Secret keyword
metadata:
  name: mongo-secret # an arbitrary name
type: Opaque # the generic type for defining Secret data key-value pairs
data: # the actual contents, the key-value pairs
  # the values in Secret are base64 encoded
  mongo-user: bW9uZ291c2Vy # mongouser encoded in base64
  mongo-password: bW9uZ29wYXNzd29yZA== # mongopassword encoded in base64
